project/models.py
from project import database


class Stock(database.Model):
    """
    Class that represents a purchased stock in a portfolio.

    The following attributes of a stock are stored in this table:
        stock symbol (type: string)
        number of shares (type: integer)
        purchase price (type: integer)

    Note: Due to a limitation in the data types supported by SQLite, the
          purchase price is stored as an integer:
              $24.10 -> 2410
              $100.00 -> 10000
              $87.65 -> 8765
    """

    __tablename__ = "stocks"

    id = database.Column(database.Integer, primary_key=True)
    stock_symbol = database.Column(database.String, nullable=False)
    number_of_shares = database.Column(database.Integer, nullable=False)
    purchase_price = database.Column(database.Integer, nullable=False)

    def __init__(self, stock_symbol: str, number_of_shares: str, purchase_price: str):
        self.stock_symbol = stock_symbol
        self.number_of_shares = int(number_of_shares)
        self.purchase_price = int(float(purchase_price) * 100)
    
    def __repr__(self):
        return f"{self.stock_symbol} - {self.number_of_shares} shares purchased at ${self.purchase_price / 100}"

project/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from logging.handlers import RotatingFileHandler
import logging
from flask.logging import default_handler
import os


#######################
#### Configuration ####
#######################

# Create the instances of the Flask extensions in the global scope,
# but without any arguments passed in. These instances are not
# attached to the Flask application at this point.
database = SQLAlchemy()
db_migration = Migrate()

######################################
#### Application Factory Function ####
######################################

def create_app():
    # Create the Flask application
    app = Flask(__name__)

    # Configure the Flask application
    config_type = os.getenv(
        "CONFIG_TYPE",
        default="config.DevelopmentConfig"
    )
    app.config.from_object(config_type)

    initialize_extensions(app)
    register_blueprints(app)
    configure_logging(app)
    register_app_callbacks(app)
    register_error_pages(app)
    return app

def register_blueprints(app):
    # Import the blueprints
    from project.stocks import stocks_blueprint
    from project.users import users_blueprint

    # Since the application instance is now created, register each Blueprint
    # with the Flask application instance (app)
    app.register_blueprint(stocks_blueprint)
    app.register_blueprint(users_blueprint, url_prefix="/users")

def configure_logging(app):
    # Logging Configuration
    file_handler = RotatingFileHandler(
        "instance/flask-stock-portfolio.log",
        maxBytes=16384,
        backupCount=20
    )
    file_formatter = logging.Formatter("%(asctime)s %(levelname)s: %(message)s [in %(filename)s:%(lineno)d]")
    file_handler.setFormatter(file_formatter)
    file_handler.setLevel(logging.INFO)
    app.logger.addHandler(file_handler)

    # Remove the default logger configured by Flask
    app.logger.removeHandler(default_handler)

    app.logger.info("Starting the Flask Stock Portfolio App...")

def register_app_callbacks(app):
    @app.before_request
    def app_before_request():
        app.logger.info("Calling before_request() for the Flask application...")

    @app.after_request
    def app_after_request(response):
        app.logger.info("Calling after_request() for the Flask application...")
        return response

    @app.teardown_request
    def app_teardown_request(error=None):
        app.logger.info("Calling teardown_request() for the Flask application...")

    @app.teardown_appcontext
    def app_teardown_appcontext(error=None):
        app.logger.info("Calling teardown_appcontext() for the Flask application...")

def register_error_pages(app):
    @app.errorhandler(404)
    def page_not_found(e):
        return render_template("404.html"), 404

    @app.errorhandler(405)
    def method_not_allowed(e):
        return render_template("405.html"), 405


########################
### Helper Functions ###
########################

def initialize_extensions(app):
    # Since the application instance is now created, pass it to each Flask
    # extension instance to bind it to the Flask application instance (app)
    database.init_app(app)
    db_migration.init_app(app, database)

project/stocks/__init__.py
"""
The stocks blueprint handles the user management for this application.
Specifically, this blueprint allows for users to add, edit, and delete
stock data from their portfolio.
"""
from flask import Blueprint

stocks_blueprint = Blueprint("stocks", __name__, template_folder="templates")

from . import routes

project/stocks/routes.py
#################
#### imports ####
#################

from . import stocks_blueprint
from flask import current_app, render_template, request, session, flash, redirect, url_for
from project.models import Stock
from project import database
import click

###########################
#### request callbacks ####
###########################

@stocks_blueprint.before_request
def stocks_before_request():
    current_app.logger.info("Calling before_request() for the stocks blueprint...")


@stocks_blueprint.after_request
def stocks_after_request(response):
    current_app.logger.info("Calling after_request() for the stocks blueprint...")
    return response


@stocks_blueprint.teardown_request
def stocks_teardown_request(error=None):
    current_app.logger.info("Calling teardown_request() for the stocks blueprint...")


################
#### routes ####
################

@stocks_blueprint.route("/")
def index():
    current_app.logger.info("Calling the index() function.")
    return render_template("stocks/index.html")

@stocks_blueprint.route("/add_stock", methods=["GET", "POST"])
def add_stock():
    if request.method == "POST":
        # Save the form data to the database
        new_stock = Stock(
            request.form["stock_symbol"],
            request.form["number_of_shares"],
            request.form["purchase_price"]
        )
        database.session.add(new_stock)
        database.session.commit()

        flash(f"Added new stock ({ request.form['stock_symbol'] })!", "success")
        current_app.logger.info(f"Added new stock ({ request.form['stock_symbol'] })!")
        return redirect(url_for("stocks.list_stocks"))

    return render_template("stocks/add_stock.html")

@stocks_blueprint.route("/stocks/")
def list_stocks():
    stocks = Stock.query.order_by(Stock.id).all()
    return render_template("stocks/stocks.html", stocks=stocks)


######################
#### cli commands ####
######################

@stocks_blueprint.cli.command("create_default_set")
def create_default_set():
    """Create three new stocks and add them to the database"""
    stock1 = Stock("HD", "25", "247.29")
    stock2 = Stock("TWTR", "230", "31.89")
    stock3 = Stock("DIS", "65", "118.77")
    database.session.add(stock1)
    database.session.add(stock2)
    database.session.add(stock3)
    database.session.commit()


@stocks_blueprint.cli.command("create")
@click.argument("symbol")
@click.argument("number_of_shares")
@click.argument("purchase_price")
def create(symbol, number_of_shares, purchase_price):
    """Create a new stock and add it to the database"""
    stock = Stock(symbol, number_of_shares, purchase_price)
    database.session.add(stock)
    database.session.commit()

project/users/__init__.py
"""
The users Blueprint handles the user management for this application.
Specifically, this Blueprint allows for new users to register and for
users to log in and to log out of the application.
"""
from flask import Blueprint

users_blueprint = Blueprint("users", __name__, template_folder="templates")

from . import routes

project/users/routes.py
#################
#### imports ####
#################
from . import users_blueprint
from flask import render_template, flash, abort

################
#### routes ####
################

@users_blueprint.route("/about")
def about():
    flash("Thanks for learning about this site!", "info")
    return render_template("/users/about.html", company_name="TestDriven.io")

@users_blueprint.errorhandler(403)
def page_forbidden(e):
    return render_template("users/403.html"), 403

@users_blueprint.route("/admin")
def admin():
    abort(403)

project/templates/405.html
{% extends "base.html" %}

{% block content %}
<h1 class="errorpage-title">Method Not Allowed (405)</h1>
<div class="errorpage-section">
    <h4>The requested method is not supported by this resource!</h4>
    <h4><a href="{{ url_for('stocks.index') }}">Flask Stock Application</a></h4>
</div>
{% endblock %}

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
        />
        <title>Flask Portfolio App</title>

        <!-- Local CSS file for styling the application -->
        <link
            rel="stylesheet"
            href="{{ url_for('static', filename='css/base_style.css') }}"
        />
        <link
            rel="shortcut icon"
            href="{{ url_for('static', filename='img/favicon.png') }}"
        />

        <!-- Additional Styling -->
        {% block styling %} {% endblock %}
    </head>
    <body>
        <header class="site-header">
            <nav class="nav">
                <a class="nav-link logo" href="{{ url_for('stocks.index') }}">
                    Flask Stock Portfolio App
                </a>
                <ul class="nav-list">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('stocks.list_stocks')}}">
                            List Stocks
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('stocks.add_stock')}}">
                            Add Stock
                        </a>
                    </li>
                </ul>
            </nav>
        </header>

        <div class="messages">
            <!-- flash messages - supported categories: success, info, error, message (default) -->
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="flash-message flash-message-{{ category }}">
                            <p>{{ message }}</p>
                            <span
                                class="close-btn"
                                onclick="this.parentElement.style.opacity=0;"
                            >
                                <svg
                                    width="12"
                                    height="12"
                                    version="1.1"
                                    viewBox="0 0 100 100"
                                    xmlns="http://www.w3.org/2000/svg"
                                >
                                    <path
                                        d="m49.941 35.891 33.531-33.531 14.168 14.168-33.531 33.414 33.531 33.531-14.168 14.168-33.531-33.531-33.414 33.531-14.168-14.168 33.531-33.531-33.531-33.414 14.168-14.168z"
                                        fill-rule="evenodd"
                                        fill="currentColor"
                                    />
                                </svg>
                            </span>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>

        <main class="content">
            <!-- child template -->
            {% block content %} {% endblock %}
        </main>

        <footer class="site-footer">
            <small>testdriven.io 2020</small>
        </footer>
    </body>
</html>